src/main/resources/crafter/studio/database-context.xml
src/main/resources/crafter/studio/database/createDDL.sql

Added scripts to initialize database tables

Database initialization

---

pom.xml
src/main/java/org/craftercms/studio/api/v1/service/content/ContentService.java
src/main/java/org/craftercms/studio/api/v1/service/site/SiteService.java
src/main/java/org/craftercms/studio/api/v1/service/why-not-in-site-configuration/DeploymentEndpointConfig.java
src/main/java/org/craftercms/studio/api/v1/service/why-not-in-site-configuration/ServicesConfig.java
src/main/java/org/craftercms/studio/api/v1/service/why-not-in-site-configuration/SiteEnvironmentConfig.java
src/main/java/org/craftercms/studio/api/v1/to/DeploymentConfigTO.java
src/main/java/org/craftercms/studio/api/v1/to/DeploymentEndpointConfigTO.java
src/main/java/org/craftercms/studio/api/v1/to/EnvironmentConfigTO.java
src/main/java/org/craftercms/studio/api/v1/to/PublishingChannelConfigTO.java
src/main/java/org/craftercms/studio/api/v1/to/PublishingChannelGroupConfigTO.java
src/main/java/org/craftercms/studio/api/v1/to/SiteConfigTO.java
src/main/java/org/craftercms/studio/api/v1/to/SiteTO.java
src/main/java/org/craftercms/studio/api/v1/to/SitesConfigTO.java
src/main/java/org/craftercms/studio/impl/v1/repository/alfresco/AlfrescoContentRepository.java
src/main/java/org/craftercms/studio/impl/v1/service/configuration/DeploymentEndpointConfigImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/configuration/ServicesConfigImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/configuration/SiteEnvironmentConfigImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/content/ContentServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/security/SecurityServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/site/SiteServiceImpl.java
src/main/resources/crafter/engine/studio-server-config.properties
src/main/resources/crafter/studio/studio-services-context.xml
src/main/webapp/default-site/scripts/api/SecurityServices.groovy
src/main/webapp/default-site/scripts/api/ServiceFactory.groovy
src/main/webapp/default-site/scripts/api/SiteServices.groovy
src/main/webapp/default-site/scripts/api/impl/site/SpringSiteServices.groovy
src/main/webapp/default-site/scripts/rest/api/1/site/get-configuration.get.groovy
src/main/webapp/default-site/static-assets/components/cstudio-common/common-api.js

Get Configuration service ported

Get Configuration

---

src/main/java/org/craftercms/studio/api/v1/service/content/ContentTypeService.java
src/main/java/org/craftercms/studio/api/v1/service/site/SiteService.java
src/main/java/org/craftercms/studio/impl/v1/repository/alfresco/AlfrescoContentRepository.java
src/main/java/org/craftercms/studio/impl/v1/service/content/ContentTypeServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/security/SecurityServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/site/SiteServiceImpl.java
src/main/webapp/default-site/scripts/rest/api/1/security/get-user-permissions.get.groovy

Get User Permissions and Get Configuration

---

src/main/webapp/default-site/static-assets/components/cstudio-admin/mods/admin-configurations.js
src/main/webapp/default-site/static-assets/components/cstudio-contextual-nav/contextual-nav.js
src/main/webapp/default-site/static-assets/components/cstudio-contextual-nav/persona.js
src/main/webapp/default-site/static-assets/components/cstudio-contextual-nav/wcm_logo.js
src/main/webapp/default-site/static-assets/components/cstudio-dashboard-widgets/analytics-dashboard.js
src/main/webapp/default-site/static-assets/components/cstudio-dialogs/select-content-type.js
src/main/webapp/default-site/static-assets/components/cstudio-forms/forms-engine.js
src/main/webapp/default-site/static-assets/components/cstudio-preview-tools/mods/analytics-panel.js
src/main/webapp/default-site/static-assets/components/cstudio-preview-tools/mods/campaigns-panel.js
src/main/webapp/default-site/static-assets/components/cstudio-preview-tools/mods/targeting-panel.js
src/main/webapp/default-site/static-assets/components/cstudio-search/gallery-search.js
src/main/webapp/default-site/static-assets/components/cstudio-search/search.js
src/main/webapp/default-site/static-assets/themes/cstudioTheme/css/global.css
src/main/webapp/default-site/templates/web/common/page-fragments/studio-context.ftl
src/main/webapp/default-site/templates/web/overlayhook.ftl

Get content at path

---

src/main/webapp/default-site/scripts/api/SecurityServices.groovy
src/main/webapp/default-site/scripts/api/impl/security/SpringSecurityServices.groovy
src/main/webapp/default-site/scripts/rest/api/1/security/get-user-roles.get.groovy
src/main/webapp/default-site/static-assets/components/cstudio-common/common-api.js
src/main/webapp/default-site/static-assets/components/cstudio-contextual-nav/wcm_dropdown.js

Get user roles

---

src/main/java/org/craftercms/studio/api/v1/dal/SiteFeed.java
src/main/java/org/craftercms/studio/api/v1/dal/SiteFeedMapper.java
src/main/java/org/craftercms/studio/api/v1/service/site/SiteService.java
src/main/java/org/craftercms/studio/impl/v1/service/site/SiteServiceImpl.java
src/main/resources/crafter/studio/database/createDDL.sql
src/main/resources/org/craftercms/studio/api/v1/dal/SiteFeedMapper.xml
src/main/webapp/default-site/scripts/api/SiteServices.groovy
src/main/webapp/default-site/scripts/rest/api/1/site/get-sites-3.get.groovy
src/main/webapp/default-site/static-assets/components/cstudio-contextual-nav/wcm_dropdown.js
src/main/webapp/default-site/static-assets/components/cstudio-dashboard-widgets/lib/wcm-dashboardwidget-common.js
src/main/webapp/default-site/templates/web/site-dashboard.ftl

Added database table for sites and basic service

get sites service

---

src/main/java/org/craftercms/studio/api/v1/service/workflow/WorkflowService.java
src/main/java/org/craftercms/studio/impl/v1/service/workflow/WorkflowServiceImpl.java
src/main/webapp/default-site/scripts/rest/api/1/workflow/get-go-live-items.get.groovy
src/main/webapp/default-site/static-assets/components/cstudio-common/common-api.js

go live queue

---

src/main/java/org/craftercms/studio/api/v1/service/content/ContentTypeService.java
src/main/java/org/craftercms/studio/api/v1/service/security/SecurityProvider.java
src/main/java/org/craftercms/studio/impl/v1/content/pipeline/PostActivityProcessor.java
src/main/java/org/craftercms/studio/impl/v1/service/content/ContentServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/content/ContentTypeServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/objectstate/ObjectStateServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/security/SecurityServiceImpl.java
src/main/webapp/default-site/scripts/api/ContentServices.groovy
src/main/webapp/default-site/scripts/api/ServiceFactory.groovy
src/main/webapp/default-site/scripts/api/impl/content/SpringContentTypeServices.groovy
src/main/webapp/default-site/scripts/rest/api/1/content/get-content-type.get.groovy
src/main/webapp/default-site/static-assets/components/cstudio-common/common-api.js
src/main/webapp/default-site/static-assets/components/cstudio-forms/forms-engine.js

service ported
fixed issue with saving content

get content type

---

src/main/webapp/default-site/static-assets/components/cstudio-contextual-nav/wcm_content.js

fixed issue with actions not showing up (permissions format change)

studio toolbar

---

src/main/webapp/default-site/scripts/api/ClipboardServices.groovy
src/main/webapp/default-site/scripts/api/ContentServices.groovy
src/main/webapp/default-site/scripts/rest/api/1/clipboard/copy-item.post.groovy
src/main/webapp/default-site/scripts/rest/api/1/content/get-pages.get.groovy
src/main/webapp/default-site/static-assets/components/cstudio-common/common-api.js
src/main/webapp/default-site/static-assets/components/cstudio-contextual-nav/wcm-site-dropdown-mods/layered-root-folder.js
src/main/webapp/default-site/static-assets/components/cstudio-contextual-nav/wcm-site-dropdown-mods/wcm-root-folder.js
src/main/webapp/default-site/static-assets/components/cstudio-dialogs/copyDialog.js

clipboard copy

---

src/main/java/org/craftercms/studio/api/v1/service/clipboard/ClipboardService.java
src/main/java/org/craftercms/studio/impl/v1/service/clipboard/ClipboardServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/dependency/DmDependencyServiceImpl.java
src/main/webapp/default-site/scripts/api/ClipboardServices.groovy
src/main/webapp/default-site/scripts/api/ContentTypeServices.groovy
src/main/webapp/default-site/scripts/api/impl/clipboard/SpringClipboardServices.groovy
src/main/webapp/default-site/scripts/api/impl/content/SpringContentTypeServices.groovy
src/main/webapp/default-site/scripts/rest/api/1/clipboard/duplicate.get.groovy
src/main/webapp/default-site/static-assets/components/cstudio-common/common-api.js

clipboard duplicate

---

src/main/java/org/craftercms/studio/api/v1/ebus/RepositoryEventMessage.java
src/main/java/org/craftercms/studio/impl/v1/deployment/PreviewDeployer.java
src/main/java/org/craftercms/studio/impl/v1/repository/alfresco/AlfrescoContentRepository.java
src/main/resources/crafter/studio/studio-services-context.xml

previewable aspect replacement (CRAFTERMS-945)

preview deployer

---

src/main/java/org/craftercms/studio/api/v1/dal/CopyToEnvironmentMapper.java
src/main/java/org/craftercms/studio/api/v1/dal/DeploymentSyncHistoryMapper.java
src/main/java/org/craftercms/studio/api/v1/dal/PublishToTarget.java
src/main/java/org/craftercms/studio/api/v1/dal/PublishToTargetMapper.java
src/main/java/org/craftercms/studio/api/v1/deployment/Deployer.java
src/main/java/org/craftercms/studio/api/v1/job/CronJobContext.java
src/main/java/org/craftercms/studio/api/v1/service/deployment/DeploymentService.java
src/main/java/org/craftercms/studio/api/v1/service/deployment/PublishingManager.java
src/main/java/org/craftercms/studio/api/v1/service/site/SiteService.java
src/main/java/org/craftercms/studio/api/v1/service/why-not-in-site-configuration/ServicesConfig.java
src/main/java/org/craftercms/studio/impl/v1/deployment/EnvironmentStoreDeployer.java
src/main/java/org/craftercms/studio/impl/v1/deployment/PreviewDeployer.java
src/main/java/org/craftercms/studio/impl/v1/deployment/SyncTargetDeployer.java
src/main/java/org/craftercms/studio/impl/v1/job/RepositoryJob.java
src/main/java/org/craftercms/studio/impl/v1/repository/alfresco/AlfrescoContentRepository.java
src/main/java/org/craftercms/studio/impl/v1/service/configuration/ServicesConfigImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/deployment/DeploymentServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/deployment/PublishingManagerImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/deployment/job/DeployContentToEnvironmentStore.java
src/main/java/org/craftercms/studio/impl/v1/service/deployment/job/PublishContentToDeploymentTarget.java
src/main/java/org/craftercms/studio/impl/v1/service/security/SecurityServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/site/SiteServiceImpl.java
src/main/resources/crafter/engine/studio-server-config.properties
src/main/resources/crafter/studio/studio-services-context.xml
src/main/resources/org/craftercms/studio/api/v1/dal/CopyToEnvironmentMapper.xml
src/main/resources/org/craftercms/studio/api/v1/dal/DeploymentSyncHistoryMapper.xml
src/main/resources/org/craftercms/studio/api/v1/dal/PublishToTargetMapper.xml

Deployment Engine

---

src/main/java/org/craftercms/studio/impl/v1/repository/alfresco/AlfrescoContentRepository.java

Changed service call to get node ref (authentication issue)

Node Ref for path

---

src/main/java/org/craftercms/studio/impl/v1/repository/alfresco/AlfrescoContentRepository.java

Changed API call used for this service

Get Content Children

---

src/main/java/org/craftercms/studio/impl/v1/service/content/ContentServiceImpl.java

Fixed content tree algorithm

---

src/main/java/org/craftercms/studio/api/v1/dal/ObjectMetadata.java
src/main/java/org/craftercms/studio/api/v1/dal/ObjectMetadataMapper.java
src/main/java/org/craftercms/studio/api/v1/service/content/ObjectMetadataManager.java
src/main/java/org/craftercms/studio/impl/v1/content/pipeline/FormDmContentProcessor.java
src/main/java/org/craftercms/studio/impl/v1/service/content/ObjectMetadataManagerImpl.java
src/main/resources/crafter/studio/database/createDDL.sql
src/main/resources/crafter/studio/studio-services-context.xml
src/main/resources/org/craftercms/studio/api/v1/dal/ObjectMetadataMapper.xml

Object metadata

---

src/main/webapp/default-site/static-assets/components/cstudio-dialogs/submit-simple.js

submit for approval

---

src/main/java/org/craftercms/studio/impl/v1/service/deployment/PublishingManagerImpl.java

Warning when checking target version removed.

Warning message removed

---

src/main/java/org/craftercms/studio/api/v1/service/why-service-objectstate/ObjectStateService.java
src/main/java/org/craftercms/studio/impl/v1/service/objectstate/ObjectStateServiceImpl.java
src/main/webapp/default-site/scripts/api/ObjectStateServices.groovy
src/main/webapp/default-site/scripts/api/ServiceFactory.groovy
src/main/webapp/default-site/scripts/api/impl/objectstate/SpringObjectStateServices.groovy
src/main/webapp/default-site/scripts/rest/api/1/content/get-item-states.get.groovy
src/main/webapp/default-site/scripts/rest/api/1/content/get-item-states.groovy
src/main/webapp/default-site/static-assets/components/cstudio-admin/mods/workflow-states.js

Implemented get item object states rest service

CRAFTERCMS-985

---

src/main/java/org/craftercms/studio/impl/v1/service/objectstate/ObjectStateServiceImpl.java
src/main/webapp/default-site/scripts/api/ObjectStateServices.groovy
src/main/webapp/default-site/scripts/api/impl/objectstate/SpringObjectStateServices.groovy
src/main/webapp/default-site/scripts/rest/api/1/content/set-item-state.groovy
src/main/webapp/default-site/scripts/rest/api/1/content/set-item-state.post.groovy

Implemented set item object state rest service

CRAFTERCMS-986

---

src/main/java/org/craftercms/studio/impl/v1/repository/alfresco/AlfrescoContentRepository.java
src/main/java/org/craftercms/studio/impl/v1/service/content/ContentServiceImpl.java
src/main/webapp/default-site/static-assets/components/cstudio-forms/controls/file-name.js

Fixed null nodeRef issue.
Improved logging.

Fixed null nodeRef issue

---

src/main/java/org/craftercms/studio/impl/v1/service/deployment/PublishingManagerImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/objectstate/ObjectStateServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/workflow/WorkflowServiceImpl.java

General lock was never released when approving content to go live.

Locking issue fix

---

src/main/java/org/craftercms/studio/impl/v1/service/content/ContentServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/deployment/PublishingManagerImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/objectstate/ObjectStateServiceImpl.java

Added method to load workflow states

Workflow states

---

src/main/java/org/craftercms/studio/impl/v1/repository/alfresco/AlfrescoContentRepository.java

getChildren using CMIS

---

src/main/webapp/default-site/static-assets/scripts/main.js
src/main/webapp/default-site/templates/web/entry.ftl
src/main/webapp/default-site/ui/.bowerrc
src/main/webapp/default-site/ui/bower.json

* Fixing user dashboard redirection

* Checking in bower.json, .bowerrc

---

src/main/webapp/default-site/static-assets/components/cstudio-contextual-nav/wcm-site-dropdown-mods/wcm-root-folder.js
src/main/webapp/default-site/static-assets/components/cstudio-contextual-nav/wcm_dropdown.js
src/main/webapp/default-site/static-assets/scripts/animator.js
src/main/webapp/default-site/static-assets/styles/temp.css
src/main/webapp/default-site/templates/web/preview.ftl
src/main/webapp/default-site/templates/web/site-dashboard.ftl
src/main/webapp/default-site/ui/scss/temp.scss
src/main/webapp/default-site/ui/scss/util/_animate.scss

* Site content panel styling & behaviour
* Uploading animate.scss

Site content & updates

---

src/main/java/org/craftercms/studio/api/v1/service/configuration/ContentTypesConfig.java
src/main/java/org/craftercms/studio/api/v1/service/content/ContentTypeService.java
src/main/java/org/craftercms/studio/impl/v1/repository/alfresco/AlfrescoContentRepository.java
src/main/java/org/craftercms/studio/impl/v1/service/configuration/ContentTypesConfigImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/content/ContentServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/content/ContentTypeServiceImpl.java
src/main/resources/crafter/engine/studio-server-config.properties
src/main/resources/crafter/studio/studio-services-context.xml
src/main/webapp/default-site/scripts/api/ContentTypeServices.groovy
src/main/webapp/default-site/scripts/api/impl/content/SpringContentTypeServices.groovy
src/main/webapp/default-site/scripts/rest/api/1/content/get-content-types.get.groovy
src/main/webapp/default-site/static-assets/components/cstudio-common/common-api.js
src/main/webapp/default-site/static-assets/components/cstudio-dialogs/select-content-type.js

Added get all content types service implementation

Get all content types service

---

src/main/java/org/craftercms/studio/api/v1/dal/CopyToEnvironmentMapper.java
src/main/java/org/craftercms/studio/api/v1/dal/DeploymentSyncHistoryMapper.java
src/main/java/org/craftercms/studio/api/v1/dal/PublishToTargetMapper.java
src/main/java/org/craftercms/studio/api/v1/service/content/ContentService.java
src/main/java/org/craftercms/studio/api/v1/service/content/ObjectMetadataManager.java
src/main/java/org/craftercms/studio/api/v1/service/why-service-objectstate/ObjectStateService.java
src/main/java/org/craftercms/studio/impl/v1/content/pipeline/PostActivityProcessor.java
src/main/java/org/craftercms/studio/impl/v1/service/content/ContentServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/content/DmRenameServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/content/ObjectMetadataManagerImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/deployment/DeploymentServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/deployment/PublishingManagerImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/deployment/job/DeployContentToEnvironmentStore.java
src/main/java/org/craftercms/studio/impl/v1/service/objectstate/ObjectStateServiceImpl.java
src/main/resources/crafter/studio/studio-services-context.xml
src/main/resources/org/craftercms/studio/api/v1/dal/CopyToEnvironmentMapper.xml
src/main/resources/org/craftercms/studio/api/v1/dal/DeploymentSyncHistoryMapper.xml
src/main/resources/org/craftercms/studio/api/v1/dal/PublishToTargetMapper.xml

Deployment

---

src/main/java/org/craftercms/studio/impl/v1/repository/alfresco/AlfrescoContentRepository.java

Alfresco content repository now using CMIS API instead of REST API

CMIS implementation

---

src/main/java/org/craftercms/studio/api/v1/util/DebugUtils.java
src/main/java/org/craftercms/studio/impl/v1/service/content/ContentServiceImpl.java

Get item tree

---

src/main/java/org/craftercms/studio/impl/v1/service/content/ContentServiceImpl.java
src/main/resources/crafter/studio/studio-services-context.xml

work in progress

---

pom.xml
src/main/java/org/craftercms/studio/api/v1/service/content/ContentService.java
src/main/java/org/craftercms/studio/api/v1/service/content/ObjectMetadataManager.java
src/main/java/org/craftercms/studio/impl/v1/content/pipeline/FormDmContentProcessor.java
src/main/java/org/craftercms/studio/impl/v1/repository/alfresco/AlfrescoContentRepository.java
src/main/java/org/craftercms/studio/impl/v1/service/content/ContentServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/content/ObjectMetadataManagerImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/objectstate/ObjectStateServiceImpl.java

Implemented using Alfresco CMIS extension

Content Locking

---

pom.xml

Dependency was failing; added alfresco public repository

Fixing build Dependency was failing

---

src/main/java/org/craftercms/studio/api/v1/service/content/ContentService.java
src/main/java/org/craftercms/studio/impl/v1/service/activity/ActivityServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/content/ContentServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/deployment/DeploymentServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/workflow/WorkflowServiceImpl.java
src/main/resources/org/craftercms/studio/api/v1/dal/ActivityFeedMapper.xml
src/main/webapp/default-site/scripts/rest/api/1/activity/get-user-activities.get.groovy

Fixed issues with filters and displaying more items than expected

My Recent Activity

---

src/main/java/org/craftercms/studio/api/v1/ebus/EBusConstants.java
src/main/java/org/craftercms/studio/api/v1/service/deployment/DeploymentService.java
src/main/java/org/craftercms/studio/impl/v1/deployment/DeployerFactory.java
src/main/java/org/craftercms/studio/impl/v1/deployment/PreviewDeployer.java
src/main/java/org/craftercms/studio/impl/v1/service/content/ContentServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/deployment/DeploymentServiceImpl.java
src/main/resources/crafter/studio/studio-services-context.xml
src/main/webapp/default-site/scripts/api/PreviewServices.groovy
src/main/webapp/default-site/scripts/api/impl/deployment/SpringDeploymentServices.groovy
src/main/webapp/default-site/scripts/rest/api/1/preview/sync-site.post.groovy
src/main/webapp/default-site/static-assets/components/cstudio-common/common-api.js

Preview sync

---

src/main/java/org/craftercms/studio/api/v1/service/content/ContentService.java
src/main/java/org/craftercms/studio/api/v1/to/ContentItemTO.java
src/main/java/org/craftercms/studio/impl/v1/service/content/ContentServiceImpl.java
src/main/webapp/default-site/scripts/api/impl/content/SpringContentServices.groovy

Populate item properties

---

src/main/java/org/craftercms/studio/impl/v1/service/site/SiteServiceImpl.java
src/main/webapp/default-site/static-assets/scripts/main.js

CRAFTERCMS-1028;CRAFTERCMS-1029

---

src/main/java/org/craftercms/studio/api/v1/service/workflow/WorkflowService.java
src/main/java/org/craftercms/studio/api/v1/to/ContentItemTO.java
src/main/java/org/craftercms/studio/impl/v1/service/content/ContentServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/site/SiteServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/workflow/WorkflowServiceImpl.java

Show in progress items bug fixed

Dashboards

---

src/main/webapp/default-site/static-assets/components/cstudio-contextual-nav/wcm_dropdown.js

Site content menu should not show up on admin-console, search or browser pages

CRAFTERCMS-1038

---

src/main/java/org/craftercms/studio/api/v1/service/content/ContentService.java
src/main/java/org/craftercms/studio/impl/v1/service/activity/ActivityServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/content/ContentServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/deployment/job/DeployContentToEnvironmentStore.java
src/main/java/org/craftercms/studio/impl/v1/service/objectstate/ObjectStateServiceImpl.java
src/main/resources/org/craftercms/studio/api/v1/dal/ActivityFeedMapper.xml
src/main/webapp/default-site/scripts/api/ContentServices.groovy
src/main/webapp/default-site/scripts/api/impl/content/SpringContentServices.groovy
src/main/webapp/default-site/scripts/rest/api/1/content/write-content.post.groovy

Ported missing code for writing assets

CRAFTERCMS-1036

---

src/main/java/org/craftercms/studio/api/v1/dal/ObjectMetadata.java
src/main/java/org/craftercms/studio/api/v1/service/workflow/WorkflowService.java
src/main/java/org/craftercms/studio/api/v1/service/workflow/context/RequestContextBuilder.java
src/main/java/org/craftercms/studio/impl/v1/content/pipeline/FormDmContentProcessor.java
src/main/java/org/craftercms/studio/impl/v1/service/workflow/WorkflowServiceImpl.java
src/main/resources/crafter/studio/studio-services-context.xml
src/main/webapp/default-site/scripts/api/WorkflowServices.groovy
src/main/webapp/default-site/scripts/api/impl/workflow/SpringWorkflowServices.groovy
src/main/webapp/default-site/scripts/rest/api/1/workflow/submit-to-go-live.post.groovy
src/main/webapp/default-site/static-assets/components/cstudio-view-controllers/approve.js
src/main/webapp/default-site/static-assets/components/cstudio-view-controllers/request-publish.js

NPE on save

---

src/main/java/org/craftercms/studio/impl/v1/service/content/ContentServiceImpl.java

Insert new object state issue addressed

Insert new object state issue addressed

---

pom.xml
src/test/java/org/craftercms/studio/testing/it/base/rest/BaseRestTest.java
src/test/java/org/craftercms/studio/testing/it/base/ui/BaseSeleniumTest.java
src/test/java/org/craftercms/studio/testing/it/base/ui/Page.java
src/test/java/org/craftercms/studio/testing/it/base/ui/PageComponent.java
src/test/java/org/craftercms/studio/testing/it/base/ui/pages/HomePage.java
src/test/java/org/craftercms/studio/testing/it/base/ui/pages/LoginPage.java
src/test/java/org/craftercms/studio/testing/it/rest/site/SitesRestTest.java
src/test/java/org/craftercms/studio/testing/it/ui/DummySeleniumTest.java
src/test/java/org/craftercms/studio/testing/it/ui/SiteAvailabilityTest.java
src/test/java/org/craftercms/studio/testing/it/ui/site/CreateSiteTest.java
src/test/resources/rest-services.xml
src/test/resources/ui.xml

Restructure the test. Make test run only when profile test is active

Pom verification + flow of build change

---

src/main/java/org/craftercms/studio/api/v1/service/dependency/DependencyRules.java
src/main/java/org/craftercms/studio/impl/v1/service/workflow/WorkflowServiceImpl.java
src/main/resources/crafter/studio/studio-services-context.xml
src/main/webapp/default-site/scripts/api/WorkflowServices.groovy
src/main/webapp/default-site/scripts/api/impl/workflow/SpringWorkflowServices.groovy
src/main/webapp/default-site/static-assets/components/cstudio-view-controllers/request-publish.js

Submit to publish

---

src/main/webapp/default-site/static-assets/components/cstudio-dialogs/upload-asset-dialog.js

CRAFTERCMS-1045 - Fixing image upload .
CRAFTERCMS-1041 - Updating when uploading from site panel in asset folder.

CRAFTERCMS-1045 - CRAFTERCMS-1041

---

src/main/java/org/craftercms/studio/impl/v1/service/content/ContentServiceImpl.java
src/main/webapp/default-site/static-assets/components/cstudio-dashboard-widgets/my-recent-activity.js

CRAFTERCMS-1039

---

src/main/java/org/craftercms/studio/api/v1/dal/ActivityFeed.java
src/main/webapp/default-site/static-assets/components/cstudio-view-controllers/approve.js

Schedule dialog

---

src/main/java/org/craftercms/studio/api/v1/service/content/ContentService.java
src/main/java/org/craftercms/studio/impl/v1/service/content/ContentServiceImpl.java
src/main/webapp/default-site/static-assets/components/cstudio-dialogs/upload-asset-dialog.js

CRAFTERCMS-1041;CRAFTERCMS-1049

Assets upload dialog

---

src/main/java/org/craftercms/studio/impl/v1/repository/disk/DiskContentRepository.java

Fixed bug that was causing infinite loop. Wrong calculation if item is folder

CRAFTERCMS-1073

---

src/main/java/org/craftercms/studio/impl/v1/repository/disk/DiskContentRepository.java
src/main/java/org/craftercms/studio/impl/v1/service/content/DmRenameServiceImpl.java

CRAFTERCMS-1086

---

src/main/java/org/craftercms/studio/api/v1/to/ContentItemTO.java
src/main/java/org/craftercms/studio/impl/v1/service/content/ContentServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/util/ContentComparatorBase.java
src/main/java/org/craftercms/studio/impl/v1/util/ContentItemOrderComparator.java

CRAFTERCMS-1064

---

src/main/java/org/craftercms/studio/api/v1/dal/DependencyMapper.java
src/main/java/org/craftercms/studio/api/v1/dal/ObjectStateMapper.java
src/main/java/org/craftercms/studio/api/v1/service/content/ObjectMetadataManager.java
src/main/java/org/craftercms/studio/api/v1/service/dependency/DmDependencyService.java
src/main/java/org/craftercms/studio/api/v1/service/objectstate/ObjectStateService.java
src/main/java/org/craftercms/studio/impl/v1/repository/disk/DiskContentRepository.java
src/main/java/org/craftercms/studio/impl/v1/service/content/ContentServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/content/ObjectMetadataManagerImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/dependency/DmDependencyServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/deployment/PublishingManagerImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/objectstate/ObjectStateServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/workflow/WorkflowServiceImpl.java
src/main/resources/org/craftercms/studio/api/v1/dal/DependencyMapper.xml
src/main/resources/org/craftercms/studio/api/v1/dal/ObjectStateMapper.xml
src/main/webapp/default-site/static-assets/components/cstudio-view-controllers/delete.js

CRAFTERCMS-1100

---

src/main/java/org/craftercms/studio/impl/v1/service/content/ContentServiceImpl.java

CRAFTERCMS-1127
Refactored populate content item properties

CRAFTERCMS-1127

---

src/main/java/org/craftercms/studio/impl/v1/content/pipeline/AssetDmContentProcessor.java
src/main/resources/crafter/studio/studio-services-context.xml

CRAFTERCMS-1126
Edit groovy script write issues

CRAFTERCMS-1126

---

src/main/java/org/craftercms/studio/impl/v1/content/pipeline/FormDmContentProcessor.java
src/main/java/org/craftercms/studio/impl/v1/service/clipboard/ClipboardServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/content/DmPageNavigationOrderServiceImpl.java
src/main/resources/crafter/studio/studio-services-context.xml
src/main/resources/org/craftercms/studio/api/v1/dal/PageNavigationOrderMapper.xml

Copy-paste issues fixed. Cut paste pending

CRAFTERCMS-1076

---

src/main/webapp/default-site/static-assets/components/cstudio-contextual-nav/wcm-site-dropdown-mods/wcm-assets-folder.js
src/main/webapp/default-site/static-assets/styles/temp.css
src/main/webapp/default-site/ui/scss/temp.scss

CRAFTERCMS-1144 - fix right click styles in static assets
CRAFTERCMS-1077 - 'Edit' and 'View' are highlighted together at first time opening the right-click

CRAFTERCMS-1144 & CRAFTERCMS-1077

---

src/main/java/org/craftercms/studio/api/v1/service/security/SecurityProvider.java
src/main/java/org/craftercms/studio/impl/v1/repository/alfresco/AlfrescoContentRepository.java
src/main/java/org/craftercms/studio/impl/v1/service/content/ContentServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/security/MappedSecurityProvider.java
src/main/java/org/craftercms/studio/impl/v1/service/security/TestSecurityProvider.java
src/main/resources/crafter/studio/studio-services-context.xml

CRAFTERCMS-1185

---

src/main/java/org/craftercms/studio/impl/v1/repository/alfresco/AlfrescoContentRepository.java
src/main/java/org/craftercms/studio/impl/v1/repository/disk/DiskContentRepository.java
src/main/java/org/craftercms/studio/impl/v1/service/content/ContentServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/site/SiteServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/workflow/WorkflowServiceImpl.java
src/main/resources/org/craftercms/studio/api/v1/dal/ObjectMetadataMapper.xml

CRAFTERCMS-1201

---

src/main/java/org/craftercms/studio/api/v1/to/VersionTO.java
src/main/java/org/craftercms/studio/impl/v1/repository/disk/DiskContentRepository.java

CRAFTERCMS-1195

---

src/main/java/org/craftercms/studio/impl/v1/service/content/ContentServiceImpl.java
src/main/webapp/default-site/static-assets/components/cstudio-templates/approve.js

CRAFTERCMS-1206

---

src/main/java/org/craftercms/studio/api/v1/ebus/EBusConstants.java
src/main/java/org/craftercms/studio/api/v1/ebus/RepositoryEventMessage.java
src/main/java/org/craftercms/studio/impl/v1/deployment/PreviewDeployer.java
src/main/java/org/craftercms/studio/impl/v1/service/content/ContentServiceImpl.java

CRAFTERCMS-1220

---

src/main/java/org/craftercms/studio/impl/v1/deployment/SyncTargetDeployer.java
src/main/java/org/craftercms/studio/impl/v1/repository/disk/DiskContentRepository.java
src/main/java/org/craftercms/studio/impl/v1/service/content/ContentServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/deployment/PublishingManagerImpl.java
src/main/webapp/default-site/static-assets/components/cstudio-view-controllers/delete.js

CRAFTERCMS-1245

---

src/main/webapp/default-site/scripts/rest/api/1/content/reorder-items.get.groovy

CRAFTERCMS-1113

---

src/main/java/org/craftercms/studio/impl/v1/repository/alfresco/AlfrescoContentRepository.java
src/main/resources/crafter/studio/database/createDDL-mysql.sql
src/main/webapp/default-site/scripts/libs/EnvironmentOverrides.groovy
src/main/webapp/default-site/scripts/rest/api/1/user/validate-token.get.groovy
src/main/webapp/default-site/static-assets/components/cstudio-common/common-api.js
src/main/webapp/default-site/templates/web/common/page-fragments/head.ftl
src/test/java/org/craftercms/studio/testing/it/base/ui/pages/HomePage.java

Added debugging, changed response. Seems to work fine now

CRAFTERCMS-1256

---

src/main/java/org/craftercms/studio/impl/v1/repository/alfresco/AlfrescoContentRepository.java

CRAFTERCMS-1268

---

src/main/java/org/craftercms/studio/impl/v1/service/workflow/WorkflowServiceImpl.java

CRAFTERCMS-1277

---

src/main/java/org/craftercms/studio/impl/v1/service/content/ContentServiceImpl.java

CRAFTERCMS-1273

---

src/main/java/org/craftercms/studio/api/v1/repository/ContentRepository.java
src/main/java/org/craftercms/studio/api/v1/service/ConfigurableServiceBase.java
src/main/java/org/craftercms/studio/api/v1/service/content/ContentService.java
src/main/java/org/craftercms/studio/api/v1/to/PermissionsConfigTO.java
src/main/java/org/craftercms/studio/api/v1/to/SiteConfigTO.java
src/main/java/org/craftercms/studio/impl/v1/repository/alfresco/AlfrescoContentRepository.java
src/main/java/org/craftercms/studio/impl/v1/repository/cached/CachedContentRepository.java
src/main/java/org/craftercms/studio/impl/v1/repository/disk/DiskContentRepository.java
src/main/java/org/craftercms/studio/impl/v1/repository/mapped/MappedContentRepository.java
src/main/java/org/craftercms/studio/impl/v1/service/configuration/ContentTypesConfigImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/configuration/DeploymentEndpointConfigImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/configuration/ServicesConfigImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/configuration/SiteEnvironmentConfigImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/content/ContentTypeServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/notification/NotificationServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/security/SecurityServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/site/SiteServiceImpl.java
src/main/resources/crafter/studio/studio-services-context.xml
src/main/webapp/default-site/scripts/rest/api/1/user/login.post.groovy
src/main/webapp/default-site/static-assets/scripts/main.js

Various configuration services
Check for updates functionality

Various configuration services

---

src/main/java/org/craftercms/studio/api/v1/service/configuration/ContentTypesConfig.java
src/main/java/org/craftercms/studio/api/v1/service/site/SiteService.java
src/main/java/org/craftercms/studio/impl/v1/repository/cached/CachedContentRepository.java
src/main/java/org/craftercms/studio/impl/v1/service/configuration/ContentTypesConfigImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/content/ContentTypeServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/notification/NotificationServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/site/SiteServiceImpl.java
src/main/resources/crafter/engine/studio-server-config.properties
src/main/resources/crafter/studio/studio-services-context.xml

CRAFTERCMS-1264
Notification service ported
Configuration:
crafter.studio.mail.from.default=default@mail.com
crafter.studio.mail.host=smtp.gmail.com
crafter.studio.mail.port=587
crafter.studio.mail.username=username
crafter.studio.mail.password=password
crafter.studio.mail.smtp.auth=true
crafter.studio.mail.smtp.starttls.enable=true

CRAFTERCMS-1264

---

src/main/java/org/craftercms/studio/api/v1/service/configuration/ServicesConfig.java
src/main/java/org/craftercms/studio/api/v1/to/ContentItemTO.java
src/main/java/org/craftercms/studio/api/v1/to/RepositoryConfigTO.java
src/main/java/org/craftercms/studio/impl/v1/deployment/SyncTargetDeployer.java
src/main/java/org/craftercms/studio/impl/v1/service/configuration/ServicesConfigImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/content/ContentServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/workflow/WorkflowServiceImpl.java

CRAFTERCMS-1252
Fixed Issue
Deployer bug fixed

CRAFTERCMS-1252

---

src/main/java/org/craftercms/studio/impl/v1/repository/disk/DiskContentRepository.java

CRAFTERCMS-1299

---

src/main/java/org/craftercms/studio/impl/v1/repository/alfresco/AlfrescoContentRepository.java
src/main/java/org/craftercms/studio/impl/v1/repository/disk/DiskContentRepository.java
src/main/java/org/craftercms/studio/impl/v1/service/security/SecurityServiceImpl.java

CRAFTERCMS-1301

---

src/main/java/org/craftercms/studio/impl/v1/repository/disk/DiskContentRepository.java
src/main/java/org/craftercms/studio/impl/v1/service/content/DmRenameServiceImpl.java

CRAFTERCMS-1287

---

src/main/java/org/craftercms/studio/impl/v1/deployment/EnvironmentStoreDeployer.java
src/main/java/org/craftercms/studio/impl/v1/service/content/ContentServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/deployment/PublishingManagerImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/workflow/WorkflowServiceImpl.java
src/main/resources/crafter/studio/studio-services-context.xml
src/main/webapp/default-site/static-assets/components/cstudio-view-controllers/delete.js

CRAFTERCMS-1307

---

src/main/java/org/craftercms/studio/api/v1/service/security/SecurityService.java
src/main/java/org/craftercms/studio/impl/v1/repository/alfresco/AlfrescoContentRepository.java
src/main/java/org/craftercms/studio/impl/v1/service/activity/ActivityServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/content/ContentServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/deployment/DeploymentServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/security/MappedSecurityProvider.java
src/main/java/org/craftercms/studio/impl/v1/service/security/SecurityServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/security/TestSecurityProvider.java
src/main/webapp/default-site/scripts/api/SecurityServices.groovy
src/main/webapp/default-site/scripts/api/impl/security/SpringSecurityServices.groovy
src/main/webapp/default-site/scripts/rest/api/1/user/logout.post.groovy
src/main/webapp/default-site/static-assets/components/cstudio-common/common-api.js
src/main/webapp/default-site/static-assets/components/cstudio-contextual-nav/logout.js
src/main/webapp/default-site/static-assets/components/cstudio-contextual-nav/wcm-site-dropdown-mods/site-selector.js
src/main/webapp/default-site/static-assets/scripts/main.js
src/main/webapp/default-site/templates/web/context-nav.ftl

CRAFTERCMS-1178

---

src/main/java/org/craftercms/studio/impl/v1/repository/alfresco/AlfrescoContentRepository.java
src/main/resources/crafter/engine/studio-server-config.properties
src/main/resources/crafter/studio/studio-alfresco-context.xml

CRAFTERCMS-1196
Fix startup issue

CRAFTERCMS-1196

---

src/main/java/org/craftercms/studio/impl/v1/repository/alfresco/AlfrescoContentRepository.java
src/main/java/org/craftercms/studio/impl/v1/repository/disk/DiskContentRepository.java
src/main/java/org/craftercms/studio/impl/v1/service/security/SecurityServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/security/TestSecurityProvider.java
src/main/resources/crafter/engine/studio-server-config.properties
src/main/resources/crafter/studio/studio-services-context.xml
src/main/webapp/default-site/static-assets/scripts/main.js
src/main/webapp/repo-bootstrap/cstudio/config/global-permission-mappings-config.xml
src/main/webapp/repo-bootstrap/cstudio/config/global-role-mappings-config.xml

CRAFTERCMS-1352;CRAFTERCMS-1351;CRAFTERCMS-1350;CRAFTERCMS-1342

Create sites group and alfresco bootstrap

---

pom.xml
src/main/java/org/craftercms/studio/impl/v1/repository/alfresco/AlfrescoContentRepository.java

CRAFTERCMS-1354

---

src/main/java/org/craftercms/studio/impl/v1/repository/alfresco/AlfrescoContentRepository.java

Startup issue

---

src/main/resources/crafter/engine/studio-server-config.properties

Fix bootstrap default

---

src/main/webapp/default-site/static-assets/components/cstudio-common/common-api.js
src/main/webapp/default-site/static-assets/components/cstudio-common/resources/en/base.js
src/main/webapp/default-site/static-assets/components/cstudio-common/resources/es/base.js
src/main/webapp/default-site/static-assets/components/cstudio-common/resources/kr/base.js
src/main/webapp/default-site/static-assets/components/cstudio-dialogs-templates/delete.html
src/main/webapp/default-site/static-assets/components/cstudio-dialogs-templates/submit-for-delete.html
src/main/webapp/default-site/static-assets/components/cstudio-view-controllers/delete.js
src/main/webapp/default-site/static-assets/components/cstudio-view-controllers/history.js
src/main/webapp/default-site/static-assets/components/cstudio-view-controllers/submit-for-delete.js

CRAFTERCMS-1365 - translation bundle support for history dialog
CRAFTERCMS-1364 - translation bundle support for delete and submit delete dialogs

CRAFTERCMS-1365 - translation bundle support for history dialog, CRAFTERCMS-1364 - translation bundle support for delete and submit delete dialogs

---

src/main/java/org/craftercms/studio/api/v1/dal/ActivityFeed.java
src/main/java/org/craftercms/studio/api/v1/service/content/ContentService.java
src/main/java/org/craftercms/studio/impl/v1/deployment/PreviewDeployer.java
src/main/java/org/craftercms/studio/impl/v1/service/content/ContentServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/deployment/PublishingManagerImpl.java
src/main/java/org/craftercms/studio/impl/v1/util/ContentUtils.java
src/main/resources/crafter/engine/rendering/main-rendering-context.xml

CRAFTERCM-1397

---

src/main/resources/crafter/engine/services/main-services-context.xml

fix spring context

---

src/main/java/org/craftercms/studio/api/v1/service/workflow/WorkflowService.java
src/main/java/org/craftercms/studio/impl/v1/service/content/ContentTypeServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/workflow/WorkflowServiceImpl.java
src/main/webapp/default-site/scripts/api/WorkflowServices.groovy
src/main/webapp/default-site/static-assets/components/cstudio-dialogs/publish-dialog.js
src/main/webapp/default-site/static-assets/components/cstudio-dialogs/reject.js

CRAFTERCMS-1413

---

src/main/java/org/craftercms/studio/impl/v1/service/content/ContentServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/content/ContentTypeServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/workflow/WorkflowServiceImpl.java

CRAFTERCMS-1407

---

src/main/java/org/craftercms/studio/impl/v1/service/site/SiteServiceImpl.java
src/main/webapp/default-site/scripts/api/ActivityServices.groovy
src/main/webapp/default-site/scripts/api/impl/activity/SpringActivityServices.groovy
src/main/webapp/default-site/scripts/rest/api/1/activity/post-activity.post.groovy
src/main/webapp/default-site/scripts/rest/api/1/content/set-item-state.post.groovy

Exposed rest service to post user activity

CRAFTERCMS-1337

---

src/main/webapp/default-site/static-assets/scripts/main.js
src/main/webapp/default-site/templates/web/entry.ftl

CRAFTERCMS-1404

---

src/main/webapp/default-site/static-assets/components/cstudio-forms/controls/uuid.js

I found an extra "=" in the value assign

Fix typo for CRAFTERCMS-1422

---

src/main/java/org/craftercms/studio/api/v1/service/workflow/WorkflowService.java
src/main/java/org/craftercms/studio/impl/v1/repository/alfresco/AlfrescoContentRepository.java
src/main/java/org/craftercms/studio/impl/v1/service/deployment/PublishingManagerImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/workflow/WorkflowServiceImpl.java
src/main/resources/crafter/engine/services/main-services-context.xml
src/main/resources/crafter/studio/studio-services-context.xml
src/main/resources/org/craftercms/studio/api/v1/dal/DependencyMapper.xml
src/main/webapp/default-site/static-assets/components/cstudio-view-controllers/request-publish.js

CRAFTERCMS-1433

---

src/main/java/org/craftercms/studio/impl/v1/repository/alfresco/AlfrescoContentRepository.java
src/main/java/org/craftercms/studio/impl/v1/service/objectstate/ObjectStateServiceImpl.java

CRAFTERCMS-1437

---

src/main/java/org/craftercms/studio/impl/v1/service/content/ContentServiceImpl.java

sysout removed

---

src/main/java/org/craftercms/studio/api/v1/dal/CopyToEnvironmentMapper.java
src/main/java/org/craftercms/studio/api/v1/service/deployment/DeploymentService.java
src/main/java/org/craftercms/studio/impl/v1/service/deployment/DeploymentServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/security/TestSecurityProvider.java
src/main/resources/crafter/engine/studio-server-config.properties
src/main/resources/crafter/studio/studio-services-context.xml
src/main/resources/org/craftercms/studio/api/v1/dal/CopyToEnvironmentMapper.xml
src/main/webapp/default-site/scripts/api/DeploymentServices.groovy
src/main/webapp/default-site/scripts/api/impl/deployment/SpringDeploymentServices.groovy
src/main/webapp/default-site/scripts/rest/api/1/deployment/get-deployment-queue.get.groovy
src/main/webapp/default-site/static-assets/components/cstudio-admin/mods/deployment-queues.css
src/main/webapp/default-site/static-assets/components/cstudio-admin/mods/deployment-queues.js
src/main/webapp/default-site/static-assets/components/cstudio-common/resources/en/base.js
src/main/webapp/repo-bootstrap/cstudio/blueprints/pluton/site-config/administration/tools.xml

MS exhange config fix: crafter.studio.mail.smtp.ehlo=false

MS Exchange config fix

---

src/main/webapp/default-site/scripts/api/SiteServices.groovy
src/main/webapp/default-site/scripts/api/impl/site/SpringSiteServices.groovy
src/main/webapp/default-site/scripts/rest/api/1/site/clear-configuration-cache.get.groovy
src/main/webapp/default-site/static-assets/components/cstudio-admin/mods/admin-configurations.js
src/main/webapp/default-site/static-assets/components/cstudio-admin/mods/deployment-queues.js
src/main/webapp/default-site/static-assets/components/cstudio-common/resources/en/base.js

clear config cache

---

src/main/java/org/craftercms/studio/impl/v1/ebus/DistributedEBusConfig.java
src/main/java/org/craftercms/studio/impl/v1/repository/alfresco/AlfrescoContentRepository.java
src/main/resources/crafter/engine/studio-server-config.properties
src/main/resources/crafter/studio/studio-ebus-context.xml

CRAFTERCMS-1441
Config bug fix

CRAFTERCMS-1441

---

src/main/java/org/craftercms/studio/api/v1/service/content/ContentService.java
src/main/java/org/craftercms/studio/impl/v1/repository/alfresco/AlfrescoContentRepository.java
src/main/java/org/craftercms/studio/impl/v1/service/activity/ActivityServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/content/ContentServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/deployment/PublishingManagerImpl.java

CRAFTERCMS-1456

---

src/main/java/org/craftercms/studio/impl/v1/service/content/ContentTypeServiceImpl.java

CRAFTERCMS-1451

---

src/main/webapp/default-site/scripts/pages/asset-upload.groovy

CRAFTERCMS-1442

---

src/main/java/org/craftercms/studio/api/v1/to/ContentItemTO.java
src/main/java/org/craftercms/studio/impl/v1/service/content/ContentServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/objectstate/ObjectStateServiceImpl.java
src/main/resources/org/craftercms/studio/api/v1/dal/ObjectMetadataMapper.xml
src/main/resources/org/craftercms/studio/api/v1/dal/ObjectStateMapper.xml

CRAFTERCMS-1491

---

src/main/java/org/craftercms/studio/api/v1/dal/SiteFeed.java
src/main/java/org/craftercms/studio/api/v1/service/objectstate/ObjectStateService.java
src/main/java/org/craftercms/studio/impl/v1/service/content/ContentServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/objectstate/ObjectStateServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/site/SiteServiceImpl.java
src/main/webapp/default-site/static-assets/ng-views/sites.html

CRAFTERCMS-1530

---

src/main/java/org/craftercms/studio/impl/v1/service/content/ContentServiceImpl.java

CRAFTERCMS-1495

---

src/main/java/org/craftercms/studio/impl/v1/deployment/SyncTargetDeployer.java

CRAFTERCMS-1524

---

src/main/java/org/craftercms/studio/impl/v1/service/content/ContentServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/deployment/PublishingManagerImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/deployment/job/PublishContentToDeploymentTarget.java

CRAFTERCMS-1532

---

src/main/java/org/craftercms/studio/impl/v1/repository/alfresco/AlfrescoContentRepository.java

CRAFTERCMS-1522

---

src/main/java/org/craftercms/studio/impl/v1/repository/alfresco/AlfrescoContentRepository.java

CRAFTERCMS-1436

---

src/main/java/org/craftercms/studio/impl/v1/service/deployment/job/DeployContentToEnvironmentStore.java
src/main/java/org/craftercms/studio/impl/v1/service/deployment/job/PublishContentToDeploymentTarget.java

CRAFTERCMS-997

---

src/main/java/org/craftercms/studio/api/v1/repository/ContentRepository.java
src/main/java/org/craftercms/studio/impl/v1/repository/alfresco/AlfrescoContentRepository.java
src/main/java/org/craftercms/studio/impl/v1/repository/cached/CachedContentRepository.java
src/main/java/org/craftercms/studio/impl/v1/repository/disk/DiskContentRepository.java
src/main/java/org/craftercms/studio/impl/v1/repository/mapped/MappedContentRepository.java
src/main/java/org/craftercms/studio/impl/v1/repository/path/PathMappedContentRepository.java
src/main/java/org/craftercms/studio/impl/v1/service/deployment/PublishingManagerImpl.java

CRAFTERCMS-1521

---

src/main/java/org/craftercms/studio/impl/v1/repository/alfresco/AlfrescoContentRepository.java
src/main/java/org/craftercms/studio/impl/v1/repository/disk/DiskContentRepository.java
src/main/java/org/craftercms/studio/impl/v1/service/content/ContentServiceImpl.java

CRAFTERCMS-1505

---

src/main/java/org/craftercms/studio/impl/v1/deployment/EnvironmentStoreDeployer.java
src/main/java/org/craftercms/studio/impl/v1/repository/alfresco/AlfrescoContentRepository.java
src/main/java/org/craftercms/studio/impl/v1/service/notification/NotificationServiceImpl.java

CRAFTERCMS-1589
Unblocked deployment. There are still more issues to fix

CRAFTERCMS-1589

---

src/main/java/org/craftercms/studio/impl/v1/repository/alfresco/AlfrescoContentRepository.java

CRAFTERCMS-1566

---

src/main/java/org/craftercms/studio/api/v1/service/security/SecurityProvider.java
src/main/java/org/craftercms/studio/impl/v1/repository/alfresco/AlfrescoContentRepository.java
src/main/java/org/craftercms/studio/impl/v1/service/security/CachedSecurityProvider.java
src/main/java/org/craftercms/studio/impl/v1/service/security/MappedSecurityProvider.java
src/main/java/org/craftercms/studio/impl/v1/service/security/TestSecurityProvider.java
src/main/java/org/craftercms/studio/impl/v1/service/site/SiteServiceImpl.java

CRAFTERCMS-1572

---

src/main/java/org/craftercms/studio/impl/v1/content/pipeline/FormDmContentProcessor.java
src/main/java/org/craftercms/studio/impl/v1/repository/alfresco/AlfrescoContentRepository.java
src/main/java/org/craftercms/studio/impl/v1/service/activity/ActivityServiceImpl.java
src/main/webapp/default-site/scripts/libs/CommonLifecycleApi.groovy

CRAFTERCMS-1573

---

src/main/java/org/craftercms/studio/impl/v1/service/notification/NotificationServiceImpl.java

CRAFTERCMS-1595

---

src/main/webapp/default-site/static-assets/components/cstudio-contextual-nav/wcm-site-dropdown-mods/wcm-assets-folder.js
src/main/webapp/default-site/static-assets/components/cstudio-contextual-nav/wcm-site-dropdown-mods/wcm-root-folder.js
src/main/webapp/default-site/static-assets/themes/cstudioTheme/css/global.css

CRAFTERCMS-1517 - Shouldn't preview a content when a content is not previewable

CRAFTERCMS-1267 - Previewable mimetypes. CRAFTERCMS-1517 - Shouldn't preview a content when a content is not previewable

---

pom.xml
src/main/java/org/craftercms/studio/api/v1/ebus/RepositoryEventContext.java
src/main/java/org/craftercms/studio/api/v1/ebus/RepositoryEventMessage.java
src/main/java/org/craftercms/studio/api/v1/service/configuration/ContentTypesConfig.java
src/main/java/org/craftercms/studio/api/v1/service/configuration/DeploymentEndpointConfig.java
src/main/java/org/craftercms/studio/api/v1/service/configuration/ServicesConfig.java
src/main/java/org/craftercms/studio/api/v1/service/configuration/SiteEnvironmentConfig.java
src/main/java/org/craftercms/studio/impl/v1/deployment/PreviewSync.java
src/main/java/org/craftercms/studio/impl/v1/service/StudioCacheContext.java
src/main/java/org/craftercms/studio/impl/v1/service/configuration/ContentTypesConfigImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/configuration/DeploymentEndpointConfigImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/configuration/ServicesConfigImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/configuration/SiteEnvironmentConfigImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/content/ContentServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/content/ContentTypeServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/dependency/DmDependencyServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/notification/NotificationServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/security/SecurityServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/site/SiteServiceImpl.java
src/main/resources/crafter/studio/studio-cluster-config.xml
src/main/resources/crafter/studio/studio-services-context.xml

site configuration using crafter cache

site configuration using crafter cache

---

pom.xml
src/main/java/org/craftercms/studio/api/v1/ebus/ClearCacheEventMessage.java
src/main/java/org/craftercms/studio/api/v1/ebus/RepositoryEventContext.java
src/main/java/org/craftercms/studio/api/v1/ebus/RepositoryEventMessage.java
src/main/java/org/craftercms/studio/api/v1/service/configuration/ContentTypesConfig.java
src/main/java/org/craftercms/studio/api/v1/service/configuration/DeploymentEndpointConfig.java
src/main/java/org/craftercms/studio/api/v1/service/configuration/ServicesConfig.java
src/main/java/org/craftercms/studio/api/v1/service/configuration/SiteEnvironmentConfig.java
src/main/java/org/craftercms/studio/impl/v1/deployment/PreviewSync.java
src/main/java/org/craftercms/studio/impl/v1/ebus/ClearConfigurationCache.java
src/main/java/org/craftercms/studio/impl/v1/service/StudioCacheContext.java
src/main/java/org/craftercms/studio/impl/v1/service/configuration/ContentTypesConfigImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/configuration/DeploymentEndpointConfigImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/configuration/ServicesConfigImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/configuration/SiteEnvironmentConfigImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/content/ContentServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/content/ContentTypeServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/dependency/DmDependencyServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/notification/NotificationServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/security/SecurityServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/site/SiteServiceImpl.java
src/main/resources/crafter/studio/studio-cluster-config.xml
src/main/resources/crafter/studio/studio-services-context.xml

CRAFTERCMS-1567

---

src/main/java/org/craftercms/studio/impl/v1/service/dependency/DmDependencyServiceImpl.java

CRAFTERCMS-1576

---

src/main/java/org/craftercms/studio/impl/v1/ebus/ClearConfigurationCache.java
src/main/java/org/craftercms/studio/impl/v1/repository/alfresco/AlfrescoContentRepository.java
src/main/java/org/craftercms/studio/impl/v1/service/clipboard/ClipboardServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/content/DmRenameServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/dependency/DmDependencyServiceImpl.java

Fixed. UI issue remains (spinning and not refresshing navigation and dashboard after paste completed

CRAFTERCMS-1617

---

src/main/java/org/craftercms/studio/api/v1/dal/ObjectStateMapper.java
src/main/java/org/craftercms/studio/api/v1/service/objectstate/ObjectStateService.java
src/main/java/org/craftercms/studio/impl/v1/ebus/ClearConfigurationCache.java
src/main/java/org/craftercms/studio/impl/v1/service/content/ContentServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/objectstate/ObjectStateServiceImpl.java
src/main/resources/org/craftercms/studio/api/v1/dal/ObjectStateMapper.xml

CRAFTERCMS-1588

---

src/main/java/org/craftercms/studio/impl/v1/service/content/ContentServiceImpl.java

CRAFTERCMS-1267

---

src/main/java/org/craftercms/studio/api/v1/constant/CStudioXmlConstants.java
src/main/java/org/craftercms/studio/api/v1/to/DeploymentEndpointConfigTO.java
src/main/java/org/craftercms/studio/api/v1/to/PublishingChannelConfigTO.java
src/main/java/org/craftercms/studio/api/v1/to/PublishingChannelGroupConfigTO.java
src/main/java/org/craftercms/studio/api/v1/to/PublishingChannelTO.java
src/main/java/org/craftercms/studio/impl/v1/repository/alfresco/AlfrescoContentRepository.java
src/main/java/org/craftercms/studio/impl/v1/service/clipboard/ClipboardServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/configuration/DeploymentEndpointConfigImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/configuration/SiteEnvironmentConfigImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/content/DmRenameServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/deployment/DeploymentServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/deployment/job/PublishContentToDeploymentTarget.java

craftercms-990

---

src/main/java/org/craftercms/studio/impl/v1/service/content/ContentServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/dependency/DmDependencyServiceImpl.java

CRAFTERCMS-1631

---

src/main/java/org/craftercms/studio/api/v1/service/content/ImportService.java
src/main/java/org/craftercms/studio/api/v1/service/site/SiteService.java
src/main/java/org/craftercms/studio/impl/v1/content/pipeline/FormDmContentProcessor.java
src/main/java/org/craftercms/studio/impl/v1/service/content/ImportServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/site/SiteServiceImpl.java
src/main/resources/crafter/engine/studio-server-config.properties
src/main/resources/crafter/studio/studio-services-context.xml
src/main/webapp/default-site/scripts/api/SiteServices.groovy
src/main/webapp/default-site/scripts/api/impl/site/SpringSiteServices.groovy
src/main/webapp/default-site/scripts/rest/api/1/site/import-site.get.groovy

craftercms-1565

---

src/main/resources/org/craftercms/studio/api/v1/dal/ObjectStateMapper.xml

CRAFTERCMS-1635

---

src/main/webapp/default-site/scripts/rest/api/1/content/get-next-item-order.get.groovy

CRAFTERCMS-1581

---

src/main/webapp/repo-bootstrap/cstudio/blueprints/pluton/site-config/content-types/page/section/form-definition.xml
src/main/webapp/repo-bootstrap/cstudio/blueprints/pluton/site-content/site/website/portfolio/index.xml
src/main/webapp/repo-bootstrap/cstudio/blueprints/pluton/site-content/site/website/services/index.xml

CRAFTERCMS-1540

---

src/main/webapp/default-site/scripts/rest/api/1/deployment/get-deployment-history.get.groovy

CRAFTERCMS1578

---

src/main/webapp/default-site/scripts/rest/api/1/deployment/get-deployment-history.get.groovy

CRAFTERCMS-1578

---

src/main/java/org/craftercms/studio/impl/v1/repository/alfresco/AlfrescoContentRepository.java
src/main/java/org/craftercms/studio/impl/v1/service/deployment/PublishingManagerImpl.java
src/main/resources/crafter/studio/studio-services-context.xml

CRAFTERCMS-1622

---

src/main/webapp/default-site/static-assets/components/cstudio-forms/controls/uuid.js

Changes to make uuid control hidden

Fixes to make uuid control hidden

---

src/main/java/org/craftercms/studio/impl/v1/service/clipboard/ClipboardServiceImpl.java
src/main/webapp/default-site/scripts/api/impl/site/SpringSiteServices.groovy
src/main/webapp/default-site/scripts/rest/api/1/clipboard/paste-item.get.groovy
src/main/webapp/default-site/static-assets/components/cstudio-common/common-api.js

CRAFTERCMS-1643

---

src/main/java/org/craftercms/studio/api/v1/constant/CStudioConstants.java
src/main/java/org/craftercms/studio/impl/v1/service/deployment/DeploymentServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/security/TestSecurityProvider.java
src/main/java/org/craftercms/studio/impl/v1/service/workflow/WorkflowServiceImpl.java
src/main/resources/crafter/studio/studio-services-context.xml
src/main/webapp/default-site/static-assets/components/cstudio-dashboard-widgets/lib/wcm-dashboardwidget-common.js
src/main/webapp/repo-bootstrap/cstudio/blueprints/angular-memory-game/site-config/permission-mappings-config.xml
src/main/webapp/repo-bootstrap/cstudio/blueprints/corporate/site-config/permission-mappings-config.xml
src/main/webapp/repo-bootstrap/cstudio/blueprints/empty/site-config/permission-mappings-config.xml
src/main/webapp/repo-bootstrap/cstudio/blueprints/pluton/site-config/permission-mappings-config.xml

CRAFTERCMS-1626

---

src/main/java/org/craftercms/studio/api/v1/service/notification/NotificationService.java
src/main/java/org/craftercms/studio/api/v1/to/NotificationConfigTO.java
src/main/java/org/craftercms/studio/impl/v1/service/notification/NotificationServiceImpl.java
src/main/java/org/craftercms/studio/impl/v1/service/workflow/WorkflowServiceImpl.java
src/main/webapp/repo-bootstrap/cstudio/blueprints/pluton/site-config/notification-config.xml

CRAFTERCMS1458

---

src/main/java/org/craftercms/studio/impl/v1/service/content/ContentTypeServiceImpl.java

CRAFTERCMS-1517

---

src/main/java/org/craftercms/studio/impl/v1/service/content/DmRenameServiceImpl.java

CRAFTERCMS-1659

---

src/main/java/org/craftercms/studio/impl/v1/service/security/TestSecurityProvider.java
src/main/java/org/craftercms/studio/impl/v1/service/workflow/WorkflowServiceImpl.java

CRAFTERCMS1529

---

src/main/java/org/craftercms/studio/impl/v1/deployment/EnvironmentStoreDeployer.java

CRAFTERCMS-1662

---

src/main/java/org/craftercms/studio/api/v1/service/notification/NotificationService.java
src/main/java/org/craftercms/studio/api/v1/to/NotificationConfigTO.java
src/main/java/org/craftercms/studio/impl/v1/service/deployment/job/DeployContentToEnvironmentStore.java
src/main/java/org/craftercms/studio/impl/v1/service/deployment/job/PublishContentToDeploymentTarget.java
src/main/java/org/craftercms/studio/impl/v1/service/notification/NotificationServiceImpl.java
src/main/resources/crafter/studio/studio-services-context.xml
src/main/webapp/repo-bootstrap/cstudio/blueprints/angular-memory-game/site-config/notification-config.xml
src/main/webapp/repo-bootstrap/cstudio/blueprints/corporate/site-config/notification-config.xml
src/main/webapp/repo-bootstrap/cstudio/blueprints/empty/site-config/notification-config.xml
src/main/webapp/repo-bootstrap/cstudio/blueprints/pluton/site-config/notification-config.xml

CRAFTERCMS-326

---

src/main/resources/log4j.xml

CRAFTERCMS-1664

---

pom.xml
src/main/java/org/craftercms/studio/impl/v1/repository/alfresco/AlfrescoContentRepository.java

CRAFTERCMS-1671

---

src/main/java/org/craftercms/studio/impl/v1/content/pipeline/FormDmContentProcessor.java
src/main/java/org/craftercms/studio/impl/v1/service/content/ContentServiceImpl.java

CRAFTERCMS-1680
